# Generated by Django 2.2.6 on 2019-10-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_method',
            field=models.CharField(choices=[('OVEN', 'Oven'), ('GRILL', 'Grill'), ('STOVE', 'Stove'), ('OTHER', 'Other')], default='OVEN', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_temp',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(default=1, max_length=25),
        ),
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.CharField(default=1, max_length=25),
        ),
        migrations.AddField(
            model_name='recipe',
            name='note',
            field=models.CharField(default=1, max_length=25),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(default=1, max_length=25),
        ),
        migrations.AddField(
            model_name='recipe',
            name='temperature_unit',
            field=models.CharField(choices=[('F', 'F'), ('C', 'C')], default='F', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='yield_amount',
            field=models.CharField(default=1, max_length=25),
        ),
        migrations.AddField(
            model_name='recipe',
            name='yield_unit',
            field=models.CharField(default=1, max_length=25),
        ),
    ]
