# Generated by Django 2.2.6 on 2019-10-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20191023_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_temp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='note',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yield_amount',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yield_unit',
            field=models.CharField(max_length=25),
        ),
    ]
