# Generated by Django 2.2.6 on 2019-10-23 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20191023_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cook_method',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cook_temp',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cook_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='directions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='note',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='temperature_unit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='yield_amount',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='yield_unit',
        ),
    ]
