# Generated by Django 2.2.6 on 2019-10-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20191023_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_method',
            field=models.CharField(choices=[('OVEN', 'Oven'), ('GRILL', 'Grill'), ('STOVE', 'Stove'), ('OTHER', 'Other')], default='OVEN', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='temperature_unit',
            field=models.CharField(choices=[('F', 'F'), ('C', 'C')], default='F', max_length=10),
        ),
    ]
