# Generated by Django 2.2.6 on 2019-10-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20191024_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
